spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    max-threads-for-peer-replication: 0

zuul:
  prefix: /api
  routes:
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301
    db-service:
      path: /db-service/**
      url: http://localhost:8300

server:
  port: 8302